# Generated by Django 4.2.1 on 2023-05-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productgallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=50)),
                ('banner_subtitle', models.CharField(max_length=50)),
                ('banner_image', models.ImageField(max_length=255, upload_to='shop/banner')),
                ('banner_url', models.URLField()),
                ('banner_alt', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
    ]
