# Generated by Django 4.1.7 on 2023-04-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_user_alter_cartitem_cart'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='User',
        ),
    ]
